env:
  browser: true
  es6: true
  jest: true
extends:
  - 'airbnb'
  - 'plugin:@typescript-eslint/eslint-recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/prop-types: 0
  no-unused-vars: 0
  # Bug with no-unused-vars rule when importing typescript types currently. Issued tracked here
  # https://github:com/typescript-eslint/typescript-eslint/issues/363:
  indent:
    - error
    - 2
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".jsx"
      - ".tsx"

settings:
  react:
    version: 'detect'
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
